services:
  - type: web
    name: tewahedo-answers
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: tewahedo-db
          property: connectionString

databases:
  - name: tewahedo-db
    databaseName: tewahedo_answers
    user: tewahedo_user
    plan: free